### ISSUE TITLE
What is the value of the pre-defined focal length?

### ISSUE THREAD

**Issue by hxwork** [ZheC/MOW#2]
Hi,

Thanks for opening source this awesome dataset. When I am trying to obtain the bbox from the given ground truths, the focal length is required. Could you please release the value of the focal length? 

Thanks in advance for your help.

**Comment by dqj5182** [comment]
Same question

**Comment by hxwork** [comment]
The bbox can be obtained by utilizing the 2D joint coordinates. Thanks.

**Comment by dqj5182** [comment]
There is no 2D joint coords in this dataset.
